### ISSUE TITLE
Call python3 not python

### ISSUE THREAD

**Issue by cdlm** [fpom/codanim#1]
Ran into a syntax error because `examples/Makefile` calls `python` when the code requires Python 3. It seems that the accepted convention is that `python` is Python 2.x (at least on Ubuntu and macOS, default installation or via Homebrew).

**Comment by fpom** [comment]
But... Python 2 is not supported any more! Is it?  ;)
(Fixed in bab578b2b002d9c8eaed0d58194dcca93053f484.)

**Comment by cdlm** [comment]
Yeah that's why you should not write `python` in a script anymore ;-)
