### ISSUE TITLE
Examples build failure

### ISSUE THREAD

**Issue by skramm** [fpom/codanim#2]
C'est surement très bête, mais je connais pas bien Python.
`$ make 1>stdout 2>stderr` (depuis le dossier `examples`)
stdout:
```
rm -f out.*
PYTHONPATH=..:$PYTHONPATH python3 heap.py
Makefile:6: recipe for target 'heap.pdf' failed
```
stderr:
```
Traceback (most recent call last):
  File "heap.py", line 1, in <module>
    from codanim.data import Heap, Struct, Value
  File "/home/sk/dev/codanim/codanim/data.py", line 81
    self.nodeid = f"{char}{num}"
                               ^
SyntaxError: invalid syntax
make: *** [heap.pdf] Error 1
```
`$PYTHONPATH` est vide, et j'ai `$ python3` qui me dit:
```
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
```

**Comment by fpom** [comment]
Les f-strings (ie, les chaînes écrites f"....") n'ont été introduites qu'avec Python 3.6, donc c'est normal.

Cf. https://docs.python.org/3/reference/lexical_analysis.html#f-strings

**Comment by skramm** [comment]
ok, merci.
J'ai réussi à installer Python3.6 mais pour pas risquer de casser ma machine (?), j'ai pas voulu changer les liens (`python3` pointe toujours sur 3.5). J'ai juste modifié le makefile: `python3.6` au lieu de  `python3`.
Mais du coup, ça peste sur `pygments` qu'il ne trouve pas... mais qui existe, mais associé à 3.5!
(dans `/usr/local/lib/python3.5/dist-packages`, ce que me dit `pip install Pygments`).

Bon, compliqué, Python ;-) Je me pencherai là-dessus plus tard...

**Comment by fpom** [comment]
L'idéal est d'installer un environnement Python dans un virtualenv, ça permet de faire cohabiter plusieurs versions de Python. Par exemple, j'aime bien la distribution Anaconda qui fait ça très bien. 
https://www.anaconda.com/
https://conda.io/projects/conda/en/latest/user-guide/getting-started.html#managing-environments

**Comment by skramm** [comment]
ok, merci, je vais essayer ça.
